SQUADS = {
    "MI": [
        {"name": "Rohit Sharma",        "role": "BAT",  "stats": "7000+ IPL runs | Avg 29 | SR 130"},
        {"name": "Suryakumar Yadav",    "role": "BAT",  "stats": "Avg 35 | SR 157 | T20 world #1"},
        {"name": "Quinton de Kock",     "role": "WK",   "stats": "Avg 32 | SR 143 | explosive opener"},
        {"name": "Ryan Rickelton",      "role": "WK",   "stats": "SA WK-bat | SR 145 | new 2026"},
        {"name": "Tilak Varma",         "role": "AR",   "stats": "Avg 38 | SR 140 | left-arm spin"},
        {"name": "Hardik Pandya",       "role": "AR",   "stats": "Captain | eco 8.9 | 75+ wkts"},
        {"name": "Sherfane Rutherford", "role": "AR",   "stats": "WI slogger | SR 160+"},
        {"name": "Will Jacks",          "role": "AR",   "stats": "Off-spin | SR 155"},
        {"name": "Mitchell Santner",    "role": "AR",   "stats": "Left-arm spin | eco 7.5"},
        {"name": "Naman Dhir",          "role": "AR",   "stats": "SR 145 | finisher"},
        {"name": "Corbin Bosch",        "role": "AR",   "stats": "SA pace AR | eco 9.0"},
        {"name": "Shardul Thakur",      "role": "BOWL", "stats": "eco 9.0 | seam | Avg 22 bat"},
        {"name": "Jasprit Bumrah",      "role": "BOWL", "stats": "165+ wkts | eco 7.4 | world class"},
        {"name": "Trent Boult",         "role": "BOWL", "stats": "91 wkts | eco 8.1 | swing king"},
        {"name": "Deepak Chahar",       "role": "BOWL", "stats": "79 wkts | eco 8.0 | powerplay swing"},
        {"name": "Mayank Markande",     "role": "BOWL", "stats": "Leg-spin | eco 8.3"},
        {"name": "Allah Ghazanfar",     "role": "BOWL", "stats": "Afghan spinner | eco 7.8"},
    ],
    "CSK": [
        {"name": "Ruturaj Gaikwad",     "role": "BAT",  "stats": "Captain | Avg 38 | SR 134"},
        {"name": "Ayush Mhatre",        "role": "BAT",  "stats": "SR 148 | aggressive young opener"},
        {"name": "MS Dhoni",            "role": "WK",   "stats": "5000+ IPL runs | SR 136 | legend"},
        {"name": "Sanju Samson",        "role": "WK",   "stats": "NEW | Avg 34 | SR 143"},
        {"name": "Sarfaraz Khan",       "role": "BAT",  "stats": "Avg 32 | SR 140 | compact"},
        {"name": "Dewald Brevis",       "role": "AR",   "stats": "SA young gun | SR 155"},
        {"name": "Shivam Dube",         "role": "AR",   "stats": "Avg 33 | SR 152 | left-arm medium"},
        {"name": "Matthew Short",       "role": "AR",   "stats": "Aus off-spin bat | SR 145"},
        {"name": "Jamie Overton",       "role": "AR",   "stats": "Eng seam AR | eco 9.2"},
        {"name": "Ramakrishna Ghosh",   "role": "AR",   "stats": "Domestic AR | bat & ball"},
        {"name": "Khaleel Ahmed",       "role": "BOWL", "stats": "Left-arm swing | eco 8.8"},
        {"name": "Noor Ahmad",          "role": "BOWL", "stats": "Left-arm wrist spin | eco 7.6"},
        {"name": "Anshul Kamboj",       "role": "BOWL", "stats": "Seam | eco 9.0"},
        {"name": "Rahul Chahar",        "role": "BOWL", "stats": "75 wkts | eco 7.9 | leg-spin"},
        {"name": "Spencer Johnson",     "role": "BOWL", "stats": "Aus left-arm pace | eco 8.7"},
        {"name": "Matt Henry",          "role": "BOWL", "stats": "NZ seam | eco 8.5"},
        {"name": "Akeal Hosein",        "role": "BOWL", "stats": "WI left-arm spin | eco 7.8"},
    ],
    "DC": [
        {"name": "KL Rahul",            "role": "WK",   "stats": "NEW | Avg 46 | SR 136 | 4000+ runs"},
        {"name": "Prithvi Shaw",        "role": "BAT",  "stats": "SR 148 | aggressive opener"},
        {"name": "Abishek Porel",       "role": "WK",   "stats": "Avg 28 | SR 138 | young WK"},
        {"name": "Karun Nair",          "role": "BAT",  "stats": "Avg 31 | SR 135"},
        {"name": "David Miller",        "role": "BAT",  "stats": "Avg 41 | SR 145 | finisher"},
        {"name": "Pathum Nissanka",     "role": "BAT",  "stats": "SL opener | Avg 34 | SR 133"},
        {"name": "Tristan Stubbs",      "role": "BAT",  "stats": "Avg 29 | SR 150 | hard-hitter"},
        {"name": "Axar Patel",          "role": "AR",   "stats": "88 wkts | left-arm spin | Avg 25"},
        {"name": "Nitish Rana",         "role": "AR",   "stats": "Left-arm spin | 1400+ runs"},
        {"name": "Ashutosh Sharma",     "role": "AR",   "stats": "Avg 28 | SR 165 | rising star"},
        {"name": "Sameer Rizvi",        "role": "AR",   "stats": "Young bat-spin AR | SR 145"},
        {"name": "Kuldeep Yadav",       "role": "BOWL", "stats": "75 wkts | eco 8.1 | chinaman"},
        {"name": "Mitchell Starc",      "role": "BOWL", "stats": "Left-arm | eco 8.0 | powerplay"},
        {"name": "T. Natarajan",        "role": "BOWL", "stats": "80 wkts | eco 8.5 | death"},
        {"name": "Mukesh Kumar",        "role": "BOWL", "stats": "eco 9.1 | seam"},
        {"name": "Kyle Jamieson",       "role": "BOWL", "stats": "NZ tall seamer | eco 8.8"},
    ],
    "PBKS": [
        {"name": "Shreyas Iyer",        "role": "BAT",  "stats": "Captain | Avg 31 | SR 129"},
        {"name": "Prabhsimran Singh",   "role": "WK",   "stats": "SR 150 | explosive opener"},
        {"name": "Shashank Singh",      "role": "BAT",  "stats": "SR 155 | clutch hitter"},
        {"name": "Nehal Wadhera",       "role": "BAT",  "stats": "Avg 28 | SR 142"},
        {"name": "Priyansh Arya",       "role": "AR",   "stats": "SR 190+ | 2025 breakout star"},
        {"name": "Marcus Stoinis",      "role": "AR",   "stats": "Avg 28 | SR 145 | pace AR"},
        {"name": "Marco Jansen",        "role": "AR",   "stats": "Left-arm tall seamer | eco 8.8"},
        {"name": "Musheer Khan",        "role": "AR",   "stats": "Left-arm spin | batting talent"},
        {"name": "Azmatullah Omarzai",  "role": "AR",   "stats": "Afghan AR | SR 140"},
        {"name": "Liam Livingstone",    "role": "AR",   "stats": "Leg-spin | SR 156 | big-hitter"},
        {"name": "Arshdeep Singh",      "role": "BOWL", "stats": "72 wkts | eco 8.7 | left-arm"},
        {"name": "Yuzvendra Chahal",    "role": "BOWL", "stats": "187 wkts | eco 7.8 | most ever"},
        {"name": "Lockie Ferguson",     "role": "BOWL", "stats": "NZ express pace | eco 8.9"},
        {"name": "Xavier Bartlett",     "role": "BOWL", "stats": "Aus right-arm pace | eco 8.5"},
        {"name": "Vyshak Vijaykumar",   "role": "BOWL", "stats": "eco 9.0 | domestic pace"},
    ],
    "KKR": [
        {"name": "Ajinkya Rahane",          "role": "BAT",  "stats": "Captain | Avg 27 | SR 123"},
        {"name": "Rinku Singh",             "role": "BAT",  "stats": "Avg 36 | SR 148 | clutch finisher"},
        {"name": "Finn Allen",              "role": "WK",   "stats": "NZ | SR 165+ | explosive"},
        {"name": "Angkrish Raghuvanshi",    "role": "BAT",  "stats": "SR 145 | emerging talent"},
        {"name": "Rovman Powell",           "role": "BAT",  "stats": "WI | SR 160+ | power hitter"},
        {"name": "Rachin Ravindra",         "role": "AR",   "stats": "NZ | left-arm spin | Avg 32"},
        {"name": "Cameron Green",           "role": "AR",   "stats": "₹25cr record signing | pace AR"},
        {"name": "Sunil Narine",            "role": "AR",   "stats": "160+ wkts | mystery spin | Avg 24"},
        {"name": "Ramandeep Singh",         "role": "AR",   "stats": "SR 145 | medium pace"},
        {"name": "Anukul Roy",              "role": "AR",   "stats": "Left-arm spin | eco 8.0"},
        {"name": "Varun Chakaravarthy",     "role": "BOWL", "stats": "80 wkts | eco 7.9 | mystery spin"},
        {"name": "Matheesha Pathirana",     "role": "BOWL", "stats": "SL slinger | eco 8.5 | death"},
        {"name": "Blessing Muzarabani",     "role": "BOWL", "stats": "Zim 6'8\" express | eco 9.0"},
        {"name": "Vaibhav Arora",           "role": "BOWL", "stats": "eco 9.0 | domestic seam"},
        {"name": "Umran Malik",             "role": "BOWL", "stats": "150+ kmph | eco 9.5"},
    ],
    "RCB": [
        {"name": "Virat Kohli",         "role": "BAT",  "stats": "7000+ IPL runs | Avg 39 | SR 131 | The King 👑", "special": "king"},
        {"name": "Rajat Patidar",       "role": "BAT",  "stats": "Captain | Avg 33 | SR 148"},
        {"name": "Devdutt Padikkal",    "role": "BAT",  "stats": "Avg 30 | SR 132 | left-hand"},
        {"name": "Phil Salt",           "role": "WK",   "stats": "Eng | SR 162 | explosive opener"},
        {"name": "Jitesh Sharma",       "role": "WK",   "stats": "SR 158 | finisher | backup WK"},
        {"name": "Tim David",           "role": "AR",   "stats": "Avg 40 | SR 162 | finisher"},
        {"name": "Venkatesh Iyer",      "role": "AR",   "stats": "Avg 28 | SR 140 | pace AR"},
        {"name": "Krunal Pandya",       "role": "AR",   "stats": "Left-arm spin | 54 wkts | Avg 22"},
        {"name": "Jacob Bethell",       "role": "AR",   "stats": "Eng left-arm spin bat | SR 145"},
        {"name": "Romario Shepherd",    "role": "AR",   "stats": "WI | SR 150+ | power hitter"},
        {"name": "Josh Hazlewood",      "role": "BOWL", "stats": "Aus | eco 7.9 | line & length"},
        {"name": "Bhuvneshwar Kumar",   "role": "BOWL", "stats": "175 wkts | eco 7.6 | swing legend"},
        {"name": "Yash Dayal",          "role": "BOWL", "stats": "Left-arm pace | eco 9.2"},
        {"name": "Suyash Sharma",       "role": "BOWL", "stats": "Leg-spin | eco 8.5 | young"},
        {"name": "Nuwan Thushara",      "role": "BOWL", "stats": "SL left-arm pace | eco 8.8"},
    ],
    "SRH": [
        {"name": "Travis Head",         "role": "BAT",  "stats": "Avg 46 | SR 191 | 2024 Orange Cap"},
        {"name": "Ishan Kishan",        "role": "WK",   "stats": "NEW | Avg 32 | SR 135"},
        {"name": "Heinrich Klaasen",    "role": "WK",   "stats": "Avg 47 | SR 185 | best finisher"},
        {"name": "Abhishek Sharma",     "role": "AR",   "stats": "Avg 38 | SR 184 | left-arm spin"},
        {"name": "Nitish Kumar Reddy",  "role": "AR",   "stats": "Avg 30 | SR 148 | future star"},
        {"name": "Liam Livingstone",    "role": "AR",   "stats": "Leg-spin | SR 156 | big-hitter"},
        {"name": "Kamindu Mendis",      "role": "AR",   "stats": "SL | slow left-arm | Avg 35"},
        {"name": "Harshal Patel",       "role": "AR",   "stats": "100+ wkts | eco 8.9 | death"},
        {"name": "Brydon Carse",        "role": "AR",   "stats": "Eng pace AR | eco 9.0"},
        {"name": "Pat Cummins",         "role": "BOWL", "stats": "Captain | Aus pace | eco 8.5"},
        {"name": "Shivam Mavi",         "role": "BOWL", "stats": "eco 9.2 | right-arm pace"},
        {"name": "Jaydev Unadkat",      "role": "BOWL", "stats": "95 wkts | eco 8.8 | left-arm"},
        {"name": "Zeeshan Ansari",      "role": "BOWL", "stats": "Left-arm spin | eco 8.0"},
        {"name": "Bhuvneshwar Kumar",   "role": "BOWL", "stats": "175 wkts | eco 7.6 | swing"},
    ],
    "RR": [
        {"name": "Yashasvi Jaiswal",        "role": "BAT",  "stats": "Avg 41 | SR 157 | 2023 star"},
        {"name": "Vaibhav Suryavanshi",     "role": "BAT",  "stats": "13-yr-old sensation | SR 185 🔥"},
        {"name": "Dhruv Jurel",             "role": "WK",   "stats": "Avg 30 | SR 138 | young WK"},
        {"name": "Shimron Hetmyer",         "role": "BAT",  "stats": "SR 162 | powerhouse finisher"},
        {"name": "Riyan Parag",             "role": "AR",   "stats": "Captain | Avg 26 | SR 139 | leg-spin"},
        {"name": "Ravindra Jadeja",         "role": "AR",   "stats": "NEW | 127 wkts | Avg 26 bat"},
        {"name": "Yudhvir Singh Charak",    "role": "AR",   "stats": "Avg 25 | eco 8.5 | pace AR"},
        {"name": "Dasun Shanaka",           "role": "AR",   "stats": "SL | hard-hitting | medium pace"},
        {"name": "Jofra Archer",            "role": "BOWL", "stats": "NEW | Eng express pace | eco 8.0"},
        {"name": "Ravi Bishnoi",            "role": "BOWL", "stats": "61 wkts | eco 8.1 | leg-spin"},
        {"name": "Sandeep Sharma",          "role": "BOWL", "stats": "95 wkts | eco 7.9 | seam"},
        {"name": "Tushar Deshpande",        "role": "BOWL", "stats": "eco 9.1 | right-arm pace"},
        {"name": "Kwena Maphaka",           "role": "BOWL", "stats": "SA young left-arm pace"},
        {"name": "Nandre Burger",           "role": "BOWL", "stats": "SA left-arm | eco 8.6 | swing"},
    ],
    "GT": [
        {"name": "Shubman Gill",    "role": "BAT",  "stats": "Captain | Avg 37 | SR 136"},
        {"name": "Jos Buttler",     "role": "WK",   "stats": "NEW | Avg 36 | SR 149 | 3500+ runs"},
        {"name": "Sai Sudharsan",   "role": "BAT",  "stats": "Avg 32 | SR 137 | consistent"},
        {"name": "Anuj Rawat",      "role": "WK",   "stats": "Avg 24 | SR 130 | backup WK"},
        {"name": "Glenn Phillips",  "role": "BAT",  "stats": "NZ | Avg 30 | SR 150 | off-spin"},
        {"name": "Shahrukh Khan",   "role": "BAT",  "stats": "SR 155 | slogger | death"},
        {"name": "Rashid Khan",     "role": "BOWL", "stats": "112 wkts | eco 6.2 | best spinner"},
        {"name": "Washington Sundar","role": "AR",  "stats": "eco 7.5 | off-spin | Avg 22"},
        {"name": "Rahul Tewatia",   "role": "AR",   "stats": "SR 145 | leg-spin | slogger"},
        {"name": "Jason Holder",    "role": "AR",   "stats": "WI | eco 8.8 | tall seamer"},
        {"name": "Kagiso Rabada",   "role": "BOWL", "stats": "107 wkts | eco 8.6 | SA pace ace"},
        {"name": "Mohammed Siraj",  "role": "BOWL", "stats": "85 wkts | eco 8.8 | pace"},
        {"name": "Prasidh Krishna", "role": "BOWL", "stats": "eco 9.0 | tall seam | bounce"},
        {"name": "Ishant Sharma",   "role": "BOWL", "stats": "Veteran | eco 9.0"},
    ],
    "LSG": [
        {"name": "Rishabh Pant",        "role": "WK",   "stats": "NEW | Avg 34 | SR 148 | 3000+ runs"},
        {"name": "Aiden Markram",       "role": "BAT",  "stats": "Avg 32 | SR 152 | off-spin option"},
        {"name": "Nicholas Pooran",     "role": "WK",   "stats": "SR 170 | aggressive finisher"},
        {"name": "Josh Inglis",         "role": "WK",   "stats": "Aus WK-bat | SR 145"},
        {"name": "Mitchell Marsh",      "role": "AR",   "stats": "Avg 30 | SR 150 | pace AR"},
        {"name": "Wanindu Hasaranga",   "role": "AR",   "stats": "75 wkts | eco 8.1 | leg-spin"},
        {"name": "Shahbaz Ahamad",      "role": "AR",   "stats": "Left-arm spin | eco 7.8"},
        {"name": "Abdul Samad",         "role": "AR",   "stats": "SR 148 | leg-spin | power hitter"},
        {"name": "Ayush Badoni",        "role": "AR",   "stats": "SR 145 | finisher | young"},
        {"name": "Mohammad Shami",      "role": "BOWL", "stats": "74 wkts | eco 8.1 | pace legend"},
        {"name": "Avesh Khan",          "role": "BOWL", "stats": "eco 9.2 | right-arm pace"},
        {"name": "Mayank Yadav",        "role": "BOWL", "stats": "150+ kmph | eco 8.3 | 2024 breakout"},
        {"name": "Anrich Nortje",       "role": "BOWL", "stats": "SA 150+ kmph | eco 8.2"},
        {"name": "Mohsin Khan",         "role": "BOWL", "stats": "Left-arm pace | eco 8.3"},
        {"name": "Arjun Tendulkar",     "role": "BOWL", "stats": "Left-arm pace | eco 9.5"},
    ],
}
